import type { Metadata } from "next";
import { Geist, Geist_Mono ,Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable : "--font-inter" ,
  subsets : ["latin"] , 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  if (session) {
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased flex min-h-screen bg-neutral-100 relative`}
        >
          <Sidebar />
          <main className="flex-1 overflow-y-auto font-inter">{children}</main>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-neutral-100`}
      >
        <div className="min-h-screen w-full bg-[#0f172a] relative">
          <div
            className="absolute inset-0 z-0"
            style={{
              background: "#0f172a",
              backgroundImage: `
        radial-gradient(circle, rgba(139,92,246,0.6) 1px, transparent 1px),
        radial-gradient(circle, rgba(59,130,246,0.4) 1px, transparent 1px),
        radial-gradient(circle, rgba(236,72,153,0.5) 1px, transparent 1px)
      `,
              backgroundSize: "20px 20px, 40px 40px, 60px 60px",
              backgroundPosition: "0 0, 10px 10px, 30px 30px",
            }}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
